version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: bsselect-db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./bsselect-postgres-setup:/docker-entrypoint-initdb.d/
